export const productData = [
  [
    {
      visible: true,
      x: 30,
      y: 36,
      position: "top",
      news: true,
      family: true,
      title: "STRÅLA",
      productType: "Lamp shade",
      regularPrice: 13,
      price: 11,
      pieces: null,
      href: "",
    },
    {
      visible: false,
      x: 17,
      y: 10,
      position: "left",
      news: true,
      family: true,
      title: "STRÅLA",
      productType: "Lamp shade",
      regularPrice: 4,
      price: 3.4,
      pieces: null,
      href: "",
    },
    {
      visible: false,
      x: 47,
      y: 20,
      position: "right",
      news: true,
      family: false,
      title: "STRÅLA",
      productType: "Lamp shade",
      regularPrice: null,
      price: 4,
      pieces: null,
      href: "",
    },
    {
      visible: false,
      x: 36,
      y: 55,
      position: "right",
      news: true,
      family: false,
      title: "STRÅLA",
      productType: "Lamp shade",
      regularPrice: null,
      price: 3.5,
      pieces: null,
      href: "",
    },
  ],
  [
    {
      visible: false,
      x: 24,
      y: 34,
      position: "top",
      news: true,
      family: false,
      title: "VINTER 2020",
      productType: "Decoration, bauble",
      regularPrice: null,
      price: 3.5,
      pieces: 4,
      href: "",
    },
    {
      visible: true,
      x: 24,
      y: 34,
      position: "right",
      news: true,
      family: false,
      title: "VINTER 2020",
      productType: "Decoration, bauble",
      regularPrice: null,
      price: 9,
      pieces: 32,
      href: "",
    },
    {
      visible: false,
      x: 22,
      y: 64,
      position: "left",
      news: true,
      family: false,
      title: "VINTER 2020",
      productType: "Hanging decoration",
      regularPrice: null,
      price: 6,
      pieces: 6,
      href: "",
    },
  ],
];
