export const products = [
  {
    artno: 90476908,
    name: "STRÅLA",
    type: "Lamp shade",
    description: "3D/dotted",
    color: "white",
    dimensions: "67 cm",
    price: {
      current: 11,
      previous: 13,
    },
    additional:
      "Cord set sold separately. Light bulb sold separately. IKEA recommends LED bulb 200 lumen chandelier opal white.",
    images: [
      { src: "images/products/90476908/STRALA_01.webp" },
      { src: "images/products/90476908/STRALA_02.webp" },
      { src: "images/products/90476908/STRALA_03.webp" },
      { src: "images/products/90476908/STRALA_04.webp" },
      { src: "images/products/90476908/STRALA_05.webp" },
    ],
    promotional: {
      news: false,
      family: true,
      valid_from: "19 Oct",
      valid_to: "15 Nov",
    },
    product_details: {
      text: [
        "Combine with a cord set and hang the shade from the ceiling as a pendant, for example over a table or in a window.",
        "Cord set is sold separately",
        "Light bulb sold separately. IKEA recommends LED bulb 200 lumen chandelier opal white.",
        "Only for indoor use.",
      ],
      designer: "IKEA of Sweden",
      materials_and_care: [
        { title: "Shade", text: "Paperboard" },
        { title: "Support bracket / Buckles:", text: "Polycarbonate plastic" },
        { title: "", text: "Wipe clean with a dry cloth." },
      ],
    },
    package_details: {
      width: "45 cm",
      height: "4 cm",
      length: "47 cm",
      weight: "0.66 kg",
      packages: 1,
    },
    breadcrumb: ["Indoor lighting", "Decorative lighting"],
    availability: {
      online: 0,
      stores: [
        {
          store: "Belfast",
          loc: "Hollywood Exchange, 306 Airport Road West",
          qty: 0,
        },
        { store: "Birmingham", loc: "Park Lane", qty: 0 },
        {
          store: "Bristol",
          loc: "Eastgate Shopping Centre, Eastgate Road",
          qty: 0,
        },
        { store: "Cardiff", loc: "Ferry Road", qty: 0 },
        { store: "Croydon", loc: "Valley Retail Park, off Purley Way", qty: 0 },
        { store: "Edinburgh", loc: "Costkea Way, Loanhead", qty: 0 },
        { store: "Exeter", loc: "1 Ikea Way", qty: 0 },
        { store: "Gateshead", loc: "Metro Park West", qty: 0 },
        { store: "Glasgow", loc: "99 Kings Inch Drive", qty: 0 },
        { store: "Greenwich", loc: "55-57 Bugsby's Way", qty: 0 },
        { store: "Lakeside", loc: "Lakeside Retail Park, Heron Way", qty: 0 },
        { store: "Leeds", loc: "Holden Ing Way", qty: 12 },
        {
          store: "Manchester",
          loc: "Wellington Rd, Ashton-Under-Lyne",
          qty: 0,
        },
        { store: "Milton Keynes", loc: "Goslington Off Bletcham Way", qty: 0 },
        { store: "Nottingham", loc: "Giltbrook Retail Park, IKEA Way", qty: 0 },
        { store: "Reading", loc: "Pincents Kiln, Calcot", qty: 0 },
        { store: "Sheffield", loc: "Sheffield Road", qty: 0 },
        { store: "Southampton", loc: "West Quay Road", qty: 0 },
        { store: "Tottenham", loc: "6 Glover Drive", qty: 0 },
        {
          store: "Warrington",
          loc: "Gemini Retail Park, 910 Europa Blvd",
          qty: 0,
        },
        { store: "Wembley", loc: "2 Drury Way, North Circular Road", qty: 0 },
      ],
    },
  },
  {
    artno: 76298709,
    name: "TEST PRODUCT",
    type: "Test Item",
    description: "3D/dotted",
    color: "white",
    dimensions: "67 cm",
    price: {
      current: 11,
      previous: 13,
    },
    additional:
      "Cord set sold separately. Light bulb sold separately. IKEA recommends LED bulb 200 lumen chandelier opal white.",
    images: [],
    promotional: {
      news: false,
      family: true,
      valid_from: "19 Oct",
      valid_to: "15 Nov",
    },
    product_details: {
      text: [
        "Combine with a cord set and hang the shade from the ceiling as a pendant, for example over a table or in a window.",
        "Cord set is sold separately",
        "Light bulb sold separately. IKEA recommends LED bulb 200 lumen chandelier opal white.",
        "Only for indoor use.",
      ],
      designer: "IKEA of Sweden",
      materials_and_care: [
        { title: "Shade", text: "Paperboard" },
        { title: "Support bracket / Buckles:", text: "Polycarbonate plastic" },
        { title: "", text: "Wipe clean with a dry cloth." },
      ],
    },
    package_details: {
      width: "45 cm",
      height: "4 cm",
      length: "47 cm",
      weight: "0.66 kg",
      packages: 1,
    },
    breadcrumb: ["Indoor lighting", "Decorative lighting"],
    availability: {
      online: 0,
      stores: [
        {
          store: "Belfast",
          loc: "Hollywood Exchange, 306 Airport Road West",
          qty: 0,
        },
        { store: "Birmingham", loc: "Park Lane", qty: 0 },
        {
          store: "Bristol",
          loc: "Eastgate Shopping Centre, Eastgate Road",
          qty: 0,
        },
        { store: "Cardiff", loc: "Ferry Road", qty: 0 },
        { store: "Croydon", loc: "Valley Retail Park, off Purley Way", qty: 0 },
        { store: "Edinburgh", loc: "Costkea Way, Loanhead", qty: 0 },
        { store: "Exeter", loc: "1 Ikea Way", qty: 0 },
        { store: "Gateshead", loc: "Metro Park West", qty: 0 },
        { store: "Glasgow", loc: "99 Kings Inch Drive", qty: 0 },
        { store: "Greenwich", loc: "55-57 Bugsby's Way", qty: 0 },
        { store: "Lakeside", loc: "Lakeside Retail Park, Heron Way", qty: 0 },
        { store: "Leeds", loc: "Holden Ing Way", qty: 12 },
        {
          store: "Manchester",
          loc: "Wellington Rd, Ashton-Under-Lyne",
          qty: 0,
        },
        { store: "Milton Keynes", loc: "Goslington Off Bletcham Way", qty: 0 },
        { store: "Nottingham", loc: "Giltbrook Retail Park, IKEA Way", qty: 0 },
        { store: "Reading", loc: "Pincents Kiln, Calcot", qty: 0 },
        { store: "Sheffield", loc: "Sheffield Road", qty: 0 },
        { store: "Southampton", loc: "West Quay Road", qty: 0 },
        { store: "Tottenham", loc: "6 Glover Drive", qty: 0 },
        {
          store: "Warrington",
          loc: "Gemini Retail Park, 910 Europa Blvd",
          qty: 0,
        },
        { store: "Wembley", loc: "2 Drury Way, North Circular Road", qty: 0 },
      ],
    },
  },
];
